services:
  back:
    build: ./back
    volumes:
      - ./back:/usr/src/back
    ports:
      - "8013:8013"
      - "8014:8014"
  front:
    build: ./front
    ports:
      - "3013:3013"
      - "3014:3014"