services:
  back:
    build: ./back
    volumes:
      - ./back:/usr/src/back
    ports:
      - "8013:8013"
      - "8014:8014"
  front:
    build: ./front
    volumes:
      - ./front:/usr/src/front
    ports:
      - "3000:3000"
      - "3001:3001"